version: "3"
services:
  frontend:
    build: ./user-system-front
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    volumes:
      - ./user-system-front:/app
    restart: always
    depends_on:
      - backend

  backend:
    build: ./user-system-api
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    volumes:
      - ./user-system-api:/app
    restart: always
    links:
      - mongo
    expose:
      - 8080

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
